### ISSUE TITLE
CLI not printing help function???

### ISSUE THREAD

**Issue by DasVinch** [milk-org/milk#15]
I was digging on replacement following the deletion of `creaimshm` et al at 7a6aa9249973e000a18407232d4aa7651c96fcd9. Which may break a number of 3-rd party scripts... TBC...

I see in the commit message that `creaimshm` is replaced with `mk2Dim` and `mk3Dim`. So far so good.

Now, the info I was really looking for, is this (from image_make2D.c):
```
// detailed help
static errno_t help_function()
{
    printf(
        "Create 2D image\n"
        "File name can be appended with attribute:\n"
        "For example: \"s>im1\", indicates a shared memory image (attribute "
        "\"s\")\n"
        "Attributes list:\n"
        "    s>      shared memory\n"
        "    k20>    number of keyword=20\n"
        "    c5>     5-deep circular buffer for logging\n"
        "    tui8>   type unsigned int 8-bit\n"
        "    tsi8>   type signed int 8-bit\n"
        "    tui16>  type unsigned int 16-bit\n"
        "    tsi16>  type signed int 16-bit\n"
        "    tui32>  type unsigned int 32-bit\n"
        "    tsi32>  type signed int 32-bit\n"
        "    tui64>  type unsigned int 64-bit\n"
        "    tf32>   type float 32-bit\n"
        "    tf64>   type float 64-bit\n");

    return RETURN_SUCCESS;
}
```

however... the CLI help only yields
```
mk2Dim in COREMOD_memory []
	make 2D image
	example> mk2Dim out1 512 512
	src: /home/vdeo/src/milk/src/COREMOD_memory/image_make2D.c
    [ ON]  FPS support
    [OFF]  processinfo support (..procinfo 0/1)

  CLI call arguments:
     0   .out_name        [  STR  ]  s>yo          output image
     1   .xsize           [ int64 ]  100           x size
     2   .ysize           [ int64 ]  100           y size
```

How do you get the CLI to yield the full help_function????

**Comment by oguyon** [comment]
To get full help of a command, type : "<cmd> ?"
To search for matching commands, type "cmd? <string>", which happens to print a short help if the string is an exact match to the command name.
How about we should change this so that cmd? also print the full help when the string is an exact match ?

**Comment by DasVinch** [comment]
Ha!! I feel silly now.

I always get it wrong with `<command>?`, because this is the default in ipython.
It never even occured to me to try `<command> ?`...
