### ISSUE TITLE
saveFITS does fail for uint8_t images

### ISSUE THREAD

**Issue by jbOhland93** [milk-org/milk#16]
Saving an image in shared memory to a fits file does not work anymore for UI8 images. Here's what happens:

- Have an image in shared memory, the datatype is uint8_t, displayed as "UI8" in milk_streamCTRL
- Start milk CLI
- >readshmim <streamname>
- >saveFITS <streamnyme> "myFits.fits"
- Get for following error:
```
FITSIO error 412 [<MILK_ROOT>/src/COREMOD_iofits/savefits.c, saveFITS_opt_trunc, 660]: datatype conversion overflow
 WARNING [ FILE: <MILK_ROOT>/src/COREMOD_iofits/savefits.c   FUNCTION: saveFITS_opt_trunc  LINE: 665 ]
No C error (errno = 0)
 data trucated
```

This does not happen for uint16_t and float images - I did not try other ones.

milk-branch: dev (commit 29f799d42126fac113d7bbebd9d45bb291f2820c)
ImageStreamIO-branch: dev (commit 2ab382dd4bb774f7aaa9ef67385278e3b53ebca2)

**Comment by DasVinch** [comment]
Noted.

Seems that the int8/uint8 saveFITS is quite broken.
- If I saveFITS uint8 zero data, then load the file in astropy, I'm finding a float32 file of value 128.....
- If I saveFITS int8 zero data, the load, I'm getting Uint8 zero data...

**Comment by DasVinch** [comment]
Find the odd one out (from the cfitsIO manual)...

```
The following 4 data type codes are also supported by CFITSIO:
#define SBYTE_IMG 10
/* 8-bit signed integers, equivalent to */
/* BITPIX = 8, BSCALE = 1, BZERO = -128 */
#define USHORT_IMG 20 /* 16-bit unsigned integers, equivalent to */
/* BITPIX = 16, BSCALE = 1, BZERO = 32768 */
#define ULONG_IMG
40 /* 32-bit unsigned integers, equivalent to */
/* BITPIX = 32, BSCALE = 1, BZERO = 2147483648 */
```

I'm writing a PR.

**Comment by jbOhland93** [comment]
Now that's funky! Is the BZERO of the 8-bit signed int set to -128 rather than 0 because the unsigned counterpart is used more frequently and having a zero is more environmentally friendly? Feels like it's worth the confusion.
