### ISSUE TITLE
fpsCTRL list with l, press any key doesn't work and enter segfaults

### ISSUE THREAD

**Issue by jaredmales** [milk-org/milk#2]
if you press `l` in milk-fpsCTRL to view all properties, when it says "press any key" only the enter key has any effect, and that causes segfault.  See screenshot.

![image](https://user-images.githubusercontent.com/7494792/154857244-bc819904-00c0-46fd-85cd-86a7e5df31d8.png)

**Comment by oguyon** [comment]
Fixed by using proper TUI reentry function: TUI_init_terminal(&wrow, &wcol);
