### ISSUE TITLE
STRINGMAXLEN_FILE_NAME’ undeclared in isio-stream-info.c

### ISSUE THREAD

**Issue by jaredmales** [milk-org/milk#20]
Freshest of fresh clones gives this:

[ 99%] Building C object src/isio-tools/isio-stream-info-1line/CMakeFiles/isio-stream-info.dir/isio-stream-info.c.o
/opt/MagAOX/source/milk/src/isio-tools/isio-stream-info-1line/isio-stream-info.c: In function ‘main’:
/opt/MagAOX/source/milk/src/isio-tools/isio-stream-info-1line/isio-stream-info.c:49:28: error: ‘STRINGMAXLEN_FILE_NAME’ undeclared (first use in this function); did you mean ‘STRINGMAXLEN_IMAGE_NAME’?
   49 |                 char fname[STRINGMAXLEN_FILE_NAME];
      |                            ^~~~~~~~~~~~~~~~~~~~~~
      |                            STRINGMAXLEN_IMAGE_NAME
/opt/MagAOX/source/milk/src/isio-tools/isio-stream-info-1line/isio-stream-info.c:49:28: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [src/isio-tools/isio-stream-info-1line/CMakeFiles/isio-stream-info.dir/build.make:76: src/isio-tools/isio-stream-info-1line/CMakeFiles/isio-stream-info.dir/isio-stream-info.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2423: src/isio-tools/isio-stream-info-1line/CMakeFiles/isio-stream-info.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by jaredmales** [comment]
I fixed this by FILE-->IMAGE.

Also, isio-stream-info.c has an `#include "ImageStreamIO/ImagestreamIO.h"` that doesn't work on a fresh install.  Just added a `../../`

**Comment by oguyon** [comment]
Issue no longer occurring - unable to reproduce. Confirmed with @jaredmales that all is now good.
Will keep an eye for it.
