### ISSUE TITLE
docs typo

### ISSUE THREAD

**Issue by jcranney** [milk-org/milk#28]
I think the separator for `milk-exec` is the semicolon `;` not the colon `:` as it says in the CLI help (see below).

https://github.com/milk-org/milk/blob/0aa9824c88a5d8134fbb9640540dd5047c5ad79a/scripts/milk-exec#L1-L9

**Comment by DasVinch** [comment]
Correct!
fix at 879cf3b353c5b623165bf58ce895a37611197999
