### ISSUE TITLE
cmake does not detect missing readline

### ISSUE THREAD

**Issue by jaredmales** [milk-org/milk#5]
on a fresh install on 22.04 don't find out readline is missing until compiling `CommandLineInterface/CLIcore.c`

**Comment by frigaut** [comment]
still the case in 12/2024

**Comment by DasVinch** [comment]
Thanks for the ping @frigaut.
I hope it should be fixed, I don't really have anything available without readline to make doublesure.

**Comment by frigaut** [comment]
Fixed indeed. thanks
