### ISSUE TITLE
[Repo arch] Merging submodules as plain folders?

### ISSUE THREAD

**Issue by DasVinch** [milk-org/milk#7]
As we're onboarding more potential contributing devs, I'm thinking for traceability to nuke the pseudo-submodule structure of the `plugins/` folder and merge all the code as simple folders, traced withing this repository.

- This would result in not having to use `fetch_milk_dev` if working only on MILK+plugins.
- ImageStreamIO would remain a full-standing submodule
- CACAO would remain a hidden submodule same as current (untracked folder, pull dev with `./fetch_cacao_dev`.

The fact that the code is additional modules and are not required for core functionality could be implemented with a compilation flag, with e.g. a `-DCORE_ONLY` option that would ignore the automatic enumeration of extra modules in the `plugins/` directory and only consider the `src/` direcotry.

Is this breaking to anyone? @a-sevin  @jaredmales ?

I would avoid merging history trees, as this would cause `pull --rebase` pain in a lot of locations.

**Comment by a-sevin** [comment]
Hard to say on my part... I'm using a old version of milk because I don't have time to follow dev and to fix the breaks...
So if this way of deployment is a problem for contributors, you have my approval. On my side, I never do to ./fetch*

**Comment by jaredmales** [comment]
this is fine for MagAO-X

**Comment by oguyon** [comment]
If we do this, should we consider merging ImageStreamIO and milk ?

ImageStreamIO is becoming  tightly connected to processinfo, and fpsCTRL (for good reasons). The module CommandLineInterface is the core of milk, and integrates streams, fps, and procinfo. 

By the way, CommandLineInterface should probably be renamed, as it does a lot more than providing a CLI. 

Thoughts ?

**Comment by a-sevin** [comment]
Sorry, I'm so late in the follow-up of the development... I'm sure you will do the better choice.
But, as everything is interconnected, it's make sense to merge everything.

I will wait this merge to try to update our interface/adaptor.

**Comment by DasVinch** [comment]
Thanks for the answers all. I'm probably gonna proceed with closing the sub-repos with a milk-merge tag, and then proceed with blending them in.

@a-sevin feel free to point or drop a tag where you're at and before the merge, and let us know if your forwarding would need anything specific to avoid a merging hell.

I wouldn't go with merging ImageStreamIO. The key reason there is that repos such as pyMilk and probably others (I'm thinking Keck probably has a copy too) use ImageStreamIO as a standalone IPC library, while remaining entirely unaware of MILK.

However... it's not excluded to have a copy of ImageStreamIO as a direct folder in milk, the main benefit being tracking changes in milk and ISIO together rather than with submodule-update commits. But in that case all changes in ISIO would need to be ported back forth to the ISIO git repo. Lots of effort.

**Comment by DasVinch** [comment]
https://github.com/milk-org/milk/pull/8#issuecomment-1433820233
